name: Cache Git LFS
description: Use cached git lfs files if found. Otherwise, retrieve from git lfs.

runs:
  using: "composite"
  steps:
    # Git LFS
    - name: Create LFS file list
      shell: bash
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

    - name: Restore LFS cache
      uses: actions/cache@v2
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

    - name: Git LFS Pull
      shell: bash
      run: |
        git lfs pull
        git add .
        git reset --hard
